# localization.py
# Версия 9.0: Исправлена ошибка KeyError и синхронизированы все ключи.

L = {
    'ru': {
        "colorama_not_found": "Библиотека 'colorama' не найдена. Пожалуйста, установите ее: pip install colorama",
        "select_language": "Выберите язык / Select Language",
        "main_menu_title": "Выберите действие:",
        "menu_1_apply": "Применить Профили / Категории",
        "menu_2_validate": "Проверить синтаксис hosts",
        "menu_3_view_hosts": "Показать содержимое hosts",
        "menu_4_delete": "Удалить примененную категорию",
        "menu_5_clear": "Удалить ВСЕ управляемые записи",
        "menu_6_backup": "Создать резервную копию (вручную)",
        "menu_7_view_logs": "Посмотреть лог действий",
        "menu_0_exit": "Выход",
        "your_choice": "Ваш выбор: ",
        "hosts_file_path": "Путь к файлу: {}",
        "view_hosts_title": "--- Текущее содержимое файла hosts ---",
        "press_enter_to_return": "\nНажмите Enter, чтобы вернуться в меню...",
        "action_cancelled": "Действие отменено.",
        "invalid_command": "Неверная команда!",
        "invalid_input": "Неверный ввод.",
        "exiting": "...Завершение работы...",
        "auto_backup_creation": "Создание автоматической резервной копии...",
        "error_reading_hosts": "НЕ УДАЛОСЬ ПРОЧИТАТЬ ФАЙЛ HOSTS!",
        "hosts_file_empty": "Файл hosts пуст.",
        # Пагинация
        "pagination_page": "Страница {} из {}",
        "pagination_controls": "[N] След. | [P] Пред. | [Q] Выход",
        # Применение правил
        "loading_profiles": "Загрузка профилей...",
        "profiles_not_found": "Профили не найдены в папке 'profiles'.",
        "applying_rules": "Применение правил...",
        "rules_applied_success": "Правила успешно применены!",
        "rules_applied_error": "Ошибка при применении правил!",
        "nothing_to_apply": "Ничего не выбрано для применения.",
        "apply_confirm": "Применить выбранные правила? (y/n): ",
        # Выбор профилей
        "selection_title": "--- Выбор профилей и категорий для применения ---",
        "profile": "Профиль",
        "category": "Категория",
        "commands_title": "Команды:",
        "command_p": "- Введите 'p' и номер, чтобы выбрать/снять весь профиль (напр., p1)",
        "command_c": "- Введите 'c' и номер, чтобы выбрать/снять категорию (напр., c3)",
        "command_apply": "- Введите 'apply', чтобы применить выбранное",
        "command_back": "- Введите 'back', чтобы вернуться в главное меню",
        # Конфликты
        "conflict_scan": "Сканирование на наличие конфликтов...",
        "no_conflicts_found": "Конфликтов не найдено. Продолжаем применение...",
        "conflicts_found_title": "ОБНАРУЖЕНЫ КОНФЛИКТЫ!",
        "conflict_domain": "Домен",
        "conflict_old_ip": "Текущий IP",
        "conflict_new_ip": "Новый IP",
        "resolve_prompt": "Выберите действие: [R] Заменить все / [K] Оставить текущие / [A] Отменить",
        # Удаление
        "delete_cat_title": "--- Удаление примененной категории ---",
        "no_applied_categories": "В файле hosts нет примененных категорий для удаления.",
        "choose_cat_to_delete": "Выберите номер категории для удаления:",
        "delete_cat_confirm": "Вы уверены, что хотите удалить категорию '{}'? (y/n): ",
        "category_deleted_success": "Категория успешно удалена!",
        "clear_confirm": "Вы уверены, что хотите удалить ВСЕ управляемые записи из hosts? (y/n): ",
        "clearing_records": "Удаление записей...",
        "clear_success": "Все управляемые записи удалены.",
        "clear_error": "Не удалось удалить записи.",
        # Резервное копирование
        "backup_created": "Резервная копия создана: {}",
        "backup_error": "Не удалось создать резервную копию.",
        # Валидатор
        "validator_title": "--- Проверка синтаксиса файла hosts ---",
        "validator_running": "Проверка файла...",
        "validator_no_errors": "Проверка завершена. Ошибок не найдено!",
        "validator_errors_found": "Проверка завершена. Найдено ошибок: {}",
        "validator_error_line": "Строка {}:",
        "validator_error_invalid_ip": "Неверный формат IP-адреса.",
        "validator_error_invalid_domain": "Неверный формат доменного имени (найдены недопустимые символы).",
        "validator_error_format": "Неправильный формат строки (ожидается 'IP домен').",
        # Логи
        "logs_title": "--- Лог действий ---",
        "logs_not_found": "Файл логов пуст или еще не создан.",
        # Sudo
        "sudo_error_title": "ОШИБКА: Команда 'sudo' не найдена.",
        "sudo_error_info": "Это часто происходит при запуске из изолированных сред, таких как PyCharm (Flatpak/Snap).",
        "sudo_error_solution": "РЕШЕНИЕ:",
        "sudo_error_step1": "1. Откройте обычный системный терминал (не в PyCharm).",
        "sudo_error_step2": "2. Перейдите в папку проекта: cd {}",
        "sudo_error_step3": "3. Запустите скрипт вручную: sudo {} main.py",
    },
    'en': {
        "colorama_not_found": "Library 'colorama' not found. Please install it: pip install colorama",
        "select_language": "Select Language",
        "main_menu_title": "Select an action:",
        "menu_1_apply": "Apply Profiles / Categories",
        "menu_2_validate": "Validate hosts syntax",
        "menu_3_view_hosts": "View hosts file content",
        "menu_4_delete": "Delete an applied category",
        "menu_5_clear": "Clear ALL managed entries",
        "menu_6_backup": "Create a backup (Manual)",
        "menu_7_view_logs": "View Action Log",
        "menu_0_exit": "Exit",
        "your_choice": "Your choice: ",
        "hosts_file_path": "Hosts file path: {}",
        "view_hosts_title": "--- Current hosts file content ---",
        "press_enter_to_return": "\nPress Enter to return to the menu...",
        "action_cancelled": "Action cancelled.",
        "invalid_command": "Invalid command!",
        "invalid_input": "Invalid input.",
        "exiting": "...Exiting...",
        "auto_backup_creation": "Creating automatic backup...",
        "error_reading_hosts": "COULD NOT READ HOSTS FILE!",
        "hosts_file_empty": "The hosts file is empty.",
        # Pagination
        "pagination_page": "Page {} of {}",
        "pagination_controls": "[N]ext | [P]revious | [Q]uit",
        # Applying rules
        "loading_profiles": "Loading profiles...",
        "profiles_not_found": "No profiles found in 'profiles' folder.",
        "applying_rules": "Applying rules...",
        "rules_applied_success": "Rules applied successfully!",
        "rules_applied_error": "Error applying rules!",
        "nothing_to_apply": "Nothing is selected to apply.",
        "apply_confirm": "Apply selected rules? (y/n): ",
        # Profile selection
        "selection_title": "--- Select profiles and categories to apply ---",
        "profile": "Profile",
        "category": "Category",
        "commands_title": "Commands:",
        "command_p": "- Enter 'p' and a number to select/deselect a whole profile (e.g., p1)",
        "command_c": "- Enter 'c' and a number to select/deselect a category (e.g., c3)",
        "command_apply": "- Enter 'apply' to apply selection",
        "command_back": "- Enter 'back' to return to the main menu",
        # Conflicts
        "conflict_scan": "Scanning for conflicts...",
        "no_conflicts_found": "No conflicts found. Proceeding with application...",
        "conflicts_found_title": "CONFLICTS DETECTED!",
        "conflict_domain": "Domain",
        "conflict_old_ip": "Current IP",
        "conflict_new_ip": "New IP",
        "resolve_prompt": "Choose action: [R]eplace All / [K]eep All Current / [A]bort",
        # Deletion
        "delete_cat_title": "--- Delete an applied category ---",
        "no_applied_categories": "No applied categories found in hosts file to delete.",
        "choose_cat_to_delete": "Enter the number of the category to delete:",
        "delete_cat_confirm": "Are you sure you want to delete the category '{}'? (y/n): ",
        "category_deleted_success": "Category deleted successfully!",
        "clear_confirm": "Are you sure you want to delete ALL managed entries from hosts file? (y/n): ",
        "clearing_records": "Clearing records...",
        "clear_success": "All managed records have been deleted.",
        "clear_error": "Failed to delete records.",
        # Backup
        "backup_created": "Backup created: {}",
        "backup_error": "Failed to create backup.",
        # Validator
        "validator_title": "--- Hosts File Syntax Validator ---",
        "validator_running": "Checking file...",
        "validator_no_errors": "Validation complete. No errors found!",
        "validator_errors_found": "Validation complete. Found {} errors:",
        "validator_error_line": "Line {}:",
        "validator_error_invalid_ip": "Invalid IP address format.",
        "validator_error_invalid_domain": "Invalid domain name format (contains illegal characters).",
        "validator_error_format": "Incorrect line format (expected 'IP domain').",
        # Logs
        "logs_title": "--- Action Log ---",
        "logs_not_found": "Log file is empty or has not been created yet.",
        # Sudo
        "sudo_error_title": "ERROR: 'sudo' command not found.",
        "sudo_error_info": "This often happens when running from sandboxed environments like PyCharm (Flatpak/Snap).",
        "sudo_error_solution": "SOLUTION:",
        "sudo_error_step1": "1. Open a standard system terminal (not inside PyCharm).",
        "sudo_error_step2": "2. Navigate to the project folder: cd {}",
        "sudo_error_step3": "3. Run the script manually: sudo {} main.py",
    }
}
